---
- name: Install Clickhouse
  hosts: clickhouse
  become: true
  handlers:
    - name: Start clickhouse service
      ansible.builtin.service:
        name: clickhouse-server
        state: started
      tags:
        - clickhouse
        - start service

  tasks:
    - name: Get clickhouse distrib
      ansible.builtin.get_url:
        url: "https://packages.clickhouse.com/deb/pool/main/c/{{ item }}/{{ item }}_{{ clickhouse_version }}_amd64.deb"
        dest: "/tmp/{{ item }}-{{ clickhouse_version }}_amd64.deb"
        mode: '0644'
      with_items: "{{ clickhouse_packages }}"
      tags:
        - clickhouse
        - distr
    
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install clickhouse packages
      ansible.builtin.command:
        cmd: "dpkg -i /tmp/{{ item }}-{{ clickhouse_version }}_amd64.deb"
      with_items: "{{ clickhouse_packages }}"
      changed_when: false
      tags:
        - clickhouse
        - distr

    - name: Allow ClickHouse to listen on all interfaces
      become: true
      ansible.builtin.lineinfile:
        path: /etc/clickhouse-server/config.xml
        regexp: '<!--[[:space:]]*<listen_host>0\.0\.0\.0</listen_host>[[:space:]]*-->'
        insertafter: '<!-- <listen_host>::</listen_host> -->'
        # line: '<listen_host>0.0.0.0</listen_host>'
        line: '<listen_host>::</listen_host>'
      notify: Start clickhouse service

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
      tags:
        - clickhouse
        - start service
    
    - name: Wait for clickhouse-server to be ready
      ansible.builtin.wait_for:
        host: localhost
        port: 8123
        delay: 10
        timeout: 60
      tags:
        - clickhouse
        - wait
    
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0
      tags:
        - clickhouse
        - db

    - name: Create table
      ansible.builtin.command: |
        clickhouse-client -q "
          CREATE TABLE logs.vector_logs (
            timestamp DateTime64(9) DEFAULT now64(),
            message String,
            source String,
            host String
          ) ENGINE = MergeTree()
          ORDER BY timestamp;
        "
      register: create_table
      failed_when: create_table.rc != 0 and create_table.rc != 82
      changed_when: create_table.rc == 0
      tags:
        - clickhouse
        - table
    
- name: Install Vector
  hosts: vector
  become: true
  handlers:
    - name: Start Vector service
      ansible.builtin.service:
        name: vector
        state: restarted
      tags:
        - vector
        - restart service
  
  tasks:
    - name: Get vector distrib
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
        dest: "/tmp/vector-{{ vector_version }}.deb"
        mode: '0644'
      tags:
        - vector
        - distr

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
    
    - name: Install vector
      ansible.builtin.command:
        cmd: "dpkg -i /tmp/vector-{{ vector_version }}.deb"
      changed_when: false
      tags:
        - vector
        - distr

    - name: Deploy vector configuration
      ansible.builtin.template:
        src: templates/vector.yaml.j2
        dest: "{{ vector_config_path }}"
        mode: '0644'
      notify: Start Vector service
      tags:
        - vector
        - config

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
      tags:
        - vector
        - restart service

- name: Install Lighthouse
  hosts: lighthouse
  become: true
  handlers:
    - name: Restart Nginx service
      ansible.builtin.service:
        name: nginx
        state: restarted
      tags:
        - Lighthouse
        - restart service Nginx

  tasks:
    - name: Install Nginx and Git
      ansible.builtin.apt:
        name:
          - nginx
          - git
        state: present
        update_cache: yes
      tags:
        - Lighthouse
        - distr

    - name: Start and enable Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
      tags:
        - Lighthouse
        - distr

    - name: Clone Lighthouse repository
      ansible.builtin.git:
        repo: 'https://github.com/VKCOM/lighthouse.git'
        dest: /var/www/lighthouse
        version: master
        depth: 1
      tags:
        - Lighthouse
        - distr

    - name: Set ownership for Lighthouse directory
      ansible.builtin.file:
        path: /var/www/lighthouse
        owner: www-data
        group: www-data
        recurse: yes
      tags:
        - Lighthouse
        - distr

    - name: Deploy Nginx configuration for Lighthouse
      ansible.builtin.template:
        src: lighthouse.conf.j2
        dest: /etc/nginx/sites-available/lighthouse
        owner: root
        group: root
        mode: '0644'
      notify: Restart Nginx service
      tags:
        - Lighthouse
        - config nginx

    - name: Enable Lighthouse site
      ansible.builtin.file:
        src: /etc/nginx/sites-available/lighthouse
        dest: /etc/nginx/sites-enabled/lighthouse
        state: link
      notify: Restart Nginx service
      tags:
        - Lighthouse
        - distr

    - name: Remove default Nginx site
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Restart Nginx service
      tags:
        - Lighthouse
        - distr