---
clickhouse:
  hosts:
    clickhouse:
      ansible_host: 111.88.251.96
vector:
  hosts:
    vector:
      ansible_host: 111.88.254.194
lighthouse:
  hosts:
    lighthouse:
      ansible_host: 111.88.251.152
