---
clickhouse:
  hosts:
    clickhouse:
      ansible_host: 51.250.94.255
vector:
  hosts:
    vector:
      ansible_host: 51.250.86.30
lighthouse:
  hosts:
    lighthouse:
      ansible_host: 51.250.15.234
